// app/servers/[slug]/opengraph-image.tsx
// Generated by: next dev
// This is the Open Graph image for server pages

import { ImageResponse } from 'next/og';
import type { Server as ServerType } from '@/lib/db/schema';
import { db } from '@/lib/db';

const interBold = fetch(
  new URL('../../public/fonts/Inter-Bold.ttf', import.meta.url),
).then((res) => res.arrayBuffer());

export async function generateImageMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const server = await db.query.servers.findFirst({
    where: { slug },
  });

  if (!server || server.status !== 'active' || !server.verified) {
    return [];
  }

  return [
    {
      id: server.slug,
      size: { width: 1200, height: 630 },
      contentType: 'image/png',
    },
  ];
}

export default async function OgImage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const [interBoldData] = await Promise.all([interBold]);

  const server = await db.query.servers.findFirst({
    where: { slug },
  });

  if (!server || server.status !== 'active' || !server.verified) {
    return new ImageResponse(
      <div style={{ fontSize: 48, color: 'white', background: 'red' }}>Server not published</div>,
      { width: 1200, height: 630 },
    );
  }

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          background: 'linear-gradient(135deg, #1e40af 0%, #3730a3 100%)',
          color: 'white',
          padding: '40px',
          textAlign: 'center',
        }}
      >
        <div style={{ fontSize: '56px', fontWeight: 700, fontFamily: 'Inter', marginBottom: '16px' }}>
          {server.name}
        </div>
        <div style={{ fontSize: '24px', opacity: 0.9 }}>Verified MCP Server</div>
      </div>
    ),
    {
      width: 1200,
      height: 630,
      fonts: [
        {
          name: 'Inter',
          data: interBoldData,
          style: 'normal',
          weight: 700,
        },
      ],
    },
  );
}
